package dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.FoodInfoData;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.FootCateBean;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.ProCateMenuService;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.ProCateService;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.SerInitProPack;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.SerInitProPackDetailListBean;

import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.FoodInfoDataDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.FootCateBeanDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.ProCateMenuServiceDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.ProCateServiceDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.SerInitProPackDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.SerInitProPackDetailListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodInfoDataDaoConfig;
    private final DaoConfig footCateBeanDaoConfig;
    private final DaoConfig proCateMenuServiceDaoConfig;
    private final DaoConfig proCateServiceDaoConfig;
    private final DaoConfig serInitProPackDaoConfig;
    private final DaoConfig serInitProPackDetailListBeanDaoConfig;

    private final FoodInfoDataDao foodInfoDataDao;
    private final FootCateBeanDao footCateBeanDao;
    private final ProCateMenuServiceDao proCateMenuServiceDao;
    private final ProCateServiceDao proCateServiceDao;
    private final SerInitProPackDao serInitProPackDao;
    private final SerInitProPackDetailListBeanDao serInitProPackDetailListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodInfoDataDaoConfig = daoConfigMap.get(FoodInfoDataDao.class).clone();
        foodInfoDataDaoConfig.initIdentityScope(type);

        footCateBeanDaoConfig = daoConfigMap.get(FootCateBeanDao.class).clone();
        footCateBeanDaoConfig.initIdentityScope(type);

        proCateMenuServiceDaoConfig = daoConfigMap.get(ProCateMenuServiceDao.class).clone();
        proCateMenuServiceDaoConfig.initIdentityScope(type);

        proCateServiceDaoConfig = daoConfigMap.get(ProCateServiceDao.class).clone();
        proCateServiceDaoConfig.initIdentityScope(type);

        serInitProPackDaoConfig = daoConfigMap.get(SerInitProPackDao.class).clone();
        serInitProPackDaoConfig.initIdentityScope(type);

        serInitProPackDetailListBeanDaoConfig = daoConfigMap.get(SerInitProPackDetailListBeanDao.class).clone();
        serInitProPackDetailListBeanDaoConfig.initIdentityScope(type);

        foodInfoDataDao = new FoodInfoDataDao(foodInfoDataDaoConfig, this);
        footCateBeanDao = new FootCateBeanDao(footCateBeanDaoConfig, this);
        proCateMenuServiceDao = new ProCateMenuServiceDao(proCateMenuServiceDaoConfig, this);
        proCateServiceDao = new ProCateServiceDao(proCateServiceDaoConfig, this);
        serInitProPackDao = new SerInitProPackDao(serInitProPackDaoConfig, this);
        serInitProPackDetailListBeanDao = new SerInitProPackDetailListBeanDao(serInitProPackDetailListBeanDaoConfig, this);

        registerDao(FoodInfoData.class, foodInfoDataDao);
        registerDao(FootCateBean.class, footCateBeanDao);
        registerDao(ProCateMenuService.class, proCateMenuServiceDao);
        registerDao(ProCateService.class, proCateServiceDao);
        registerDao(SerInitProPack.class, serInitProPackDao);
        registerDao(SerInitProPackDetailListBean.class, serInitProPackDetailListBeanDao);
    }
    
    public void clear() {
        foodInfoDataDaoConfig.clearIdentityScope();
        footCateBeanDaoConfig.clearIdentityScope();
        proCateMenuServiceDaoConfig.clearIdentityScope();
        proCateServiceDaoConfig.clearIdentityScope();
        serInitProPackDaoConfig.clearIdentityScope();
        serInitProPackDetailListBeanDaoConfig.clearIdentityScope();
    }

    public FoodInfoDataDao getFoodInfoDataDao() {
        return foodInfoDataDao;
    }

    public FootCateBeanDao getFootCateBeanDao() {
        return footCateBeanDao;
    }

    public ProCateMenuServiceDao getProCateMenuServiceDao() {
        return proCateMenuServiceDao;
    }

    public ProCateServiceDao getProCateServiceDao() {
        return proCateServiceDao;
    }

    public SerInitProPackDao getSerInitProPackDao() {
        return serInitProPackDao;
    }

    public SerInitProPackDetailListBeanDao getSerInitProPackDetailListBeanDao() {
        return serInitProPackDetailListBeanDao;
    }

}
