package dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.FootInfo;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.bean.ProCateService;

import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.FootInfoDao;
import dq.lovemusic.thinkpad.lelaohuidatabaselibrary.dao.ProCateServiceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig footInfoDaoConfig;
    private final DaoConfig proCateServiceDaoConfig;

    private final FootInfoDao footInfoDao;
    private final ProCateServiceDao proCateServiceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        footInfoDaoConfig = daoConfigMap.get(FootInfoDao.class).clone();
        footInfoDaoConfig.initIdentityScope(type);

        proCateServiceDaoConfig = daoConfigMap.get(ProCateServiceDao.class).clone();
        proCateServiceDaoConfig.initIdentityScope(type);

        footInfoDao = new FootInfoDao(footInfoDaoConfig, this);
        proCateServiceDao = new ProCateServiceDao(proCateServiceDaoConfig, this);

        registerDao(FootInfo.class, footInfoDao);
        registerDao(ProCateService.class, proCateServiceDao);
    }
    
    public void clear() {
        footInfoDaoConfig.clearIdentityScope();
        proCateServiceDaoConfig.clearIdentityScope();
    }

    public FootInfoDao getFootInfoDao() {
        return footInfoDao;
    }

    public ProCateServiceDao getProCateServiceDao() {
        return proCateServiceDao;
    }

}
